import type * as React from "react"

import {
  BadgeCatalogDemo,
  ButtonCatalogDemo,
  ButtonGroupCatalogDemo,
  CardCatalogDemo,
  CheckboxCatalogDemo,
  CommandCatalogDemo,
  DialogCatalogDemo,
  DropdownMenuCatalogDemo,
  EmptyCatalogDemo,
  FieldCatalogDemo,
  InputCatalogDemo,
  InputGroupCatalogDemo,
  ItemCatalogDemo,
  LabelCatalogDemo,
  PopoverCatalogDemo,
  RadioGroupCatalogDemo,
  ScrollAreaCatalogDemo,
  SelectCatalogDemo,
  SeparatorCatalogDemo,
  SliderCatalogDemo,
  SpinnerCatalogDemo,
  SwitchCatalogDemo,
  TextareaCatalogDemo,
  TooltipCatalogDemo,
} from "@/components/catalog/demos/catalog-demos"
import {
  badgeSource,
  buttonGroupSource,
  buttonSource,
  cardSource,
  checkboxSource,
  commandSource,
  dialogSource,
  dropdownMenuSource,
  emptySource,
  fieldSource,
  inputGroupSource,
  inputSource,
  itemSource,
  labelSource,
  popoverSource,
  radioGroupSource,
  scrollAreaSource,
  selectSource,
  separatorSource,
  sliderSource,
  spinnerSource,
  switchSource,
  textareaSource,
  tooltipSource,
} from "@/components/catalog/demos/catalog-demo-sources"

export type CatalogEntry = {
  id: string
  title: string
  description: string
  sourcePath: string
  docsHref?: string
  preview: React.ComponentType
  /** Source snippet shown in the Code tab. */
  source: string
  notes?: string
}

const docs = (slug: string) => `https://ui.shadcn.com/docs/components/${slug}`

export const catalogEntries: CatalogEntry[] = [
  {
    id: "badge",
    title: "Badge",
    description: "Compact status labels with soft glass emphasis.",
    sourcePath: "components/ui/badge.tsx",
    docsHref: docs("badge"),
    preview: BadgeCatalogDemo,
    source: badgeSource,
  },
  {
    id: "button",
    title: "Button",
    description: "Primary actions and icon controls with frosted states.",
    sourcePath: "components/ui/button.tsx",
    docsHref: docs("button"),
    preview: ButtonCatalogDemo,
    source: buttonSource,
  },
  {
    id: "button-group",
    title: "Button Group",
    description: "Segmented action clusters tuned for glass layouts.",
    sourcePath: "components/ui/button-group.tsx",
    docsHref: docs("button-group"),
    preview: ButtonGroupCatalogDemo,
    source: buttonGroupSource,
  },
  {
    id: "card",
    title: "Card",
    description: "Structured content surfaces for dashboards and settings.",
    sourcePath: "components/ui/card.tsx",
    docsHref: docs("card"),
    preview: CardCatalogDemo,
    source: cardSource,
  },
  {
    id: "checkbox",
    title: "Checkbox",
    description: "Compact binary controls with a softened translucent fill.",
    sourcePath: "components/ui/checkbox.tsx",
    docsHref: docs("checkbox"),
    preview: CheckboxCatalogDemo,
    source: checkboxSource,
  },
  {
    id: "empty",
    title: "Empty",
    description: "Calm empty states with supportive calls to action.",
    sourcePath: "components/ui/empty.tsx",
    docsHref: docs("empty"),
    preview: EmptyCatalogDemo,
    source: emptySource,
  },
  {
    id: "item",
    title: "Item",
    description: "Composable rows for lists, cards, and navigation cells.",
    sourcePath: "components/ui/item.tsx",
    docsHref: docs("item"),
    preview: ItemCatalogDemo,
    source: itemSource,
  },
  {
    id: "separator",
    title: "Separator",
    description: "Low-contrast dividers that preserve surface rhythm.",
    sourcePath: "components/ui/separator.tsx",
    docsHref: docs("separator"),
    preview: SeparatorCatalogDemo,
    source: separatorSource,
  },
  {
    id: "spinner",
    title: "Spinner",
    description: "Loading indicators that blend into glass controls.",
    sourcePath: "components/ui/spinner.tsx",
    docsHref: docs("spinner"),
    preview: SpinnerCatalogDemo,
    source: spinnerSource,
  },
  {
    id: "field",
    title: "Field",
    description: "High-level form composition for labels, descriptions, and states.",
    sourcePath: "components/ui/field.tsx",
    docsHref: docs("field"),
    preview: FieldCatalogDemo,
    source: fieldSource,
    notes:
      "Use Field when you want labels, descriptions, grouped controls, and validation messaging to share one glass-aware structure.",
  },
  {
    id: "input",
    title: "Input",
    description: "Single-line text entry with translucent focus treatment.",
    sourcePath: "components/ui/input.tsx",
    docsHref: docs("input"),
    preview: InputCatalogDemo,
    source: inputSource,
  },
  {
    id: "input-group",
    title: "Input Group",
    description: "Composes inputs, icons, and buttons into one surface.",
    sourcePath: "components/ui/input-group.tsx",
    docsHref: docs("input-group"),
    preview: InputGroupCatalogDemo,
    source: inputGroupSource,
    notes:
      "Best for command bars, search fields, and mixed-action inputs where controls should read as a single glass surface.",
  },
  {
    id: "label",
    title: "Label",
    description: "Typographic labels sized to pair with glass form controls.",
    sourcePath: "components/ui/label.tsx",
    docsHref: docs("label"),
    preview: LabelCatalogDemo,
    source: labelSource,
  },
  {
    id: "radio-group",
    title: "Radio Group",
    description: "Single-choice selection with translucent option controls.",
    sourcePath: "components/ui/radio-group.tsx",
    docsHref: docs("radio-group"),
    preview: RadioGroupCatalogDemo,
    source: radioGroupSource,
  },
  {
    id: "select",
    title: "Select",
    description: "Popover-backed selection lists with frosted menus.",
    sourcePath: "components/ui/select.tsx",
    docsHref: docs("select"),
    preview: SelectCatalogDemo,
    source: selectSource,
  },
  {
    id: "slider",
    title: "Slider",
    description: "Range control with translucent tracks and tactile handles.",
    sourcePath: "components/ui/slider.tsx",
    docsHref: docs("slider"),
    preview: SliderCatalogDemo,
    source: sliderSource,
  },
  {
    id: "switch",
    title: "Switch",
    description: "Compact toggles with softened translucent rails.",
    sourcePath: "components/ui/switch.tsx",
    docsHref: docs("switch"),
    preview: SwitchCatalogDemo,
    source: switchSource,
  },
  {
    id: "textarea",
    title: "Textarea",
    description: "Multi-line entry with the same softened glass fill.",
    sourcePath: "components/ui/textarea.tsx",
    docsHref: docs("textarea"),
    preview: TextareaCatalogDemo,
    source: textareaSource,
  },
  {
    id: "dialog",
    title: "Dialog",
    description: "Modal surfaces with heavy blur and strong focus framing.",
    sourcePath: "components/ui/dialog.tsx",
    docsHref: docs("dialog"),
    preview: DialogCatalogDemo,
    source: dialogSource,
  },
  {
    id: "dropdown-menu",
    title: "Dropdown Menu",
    description: "Contextual action lists rendered as frosted menus.",
    sourcePath: "components/ui/dropdown-menu.tsx",
    docsHref: docs("dropdown-menu"),
    preview: DropdownMenuCatalogDemo,
    source: dropdownMenuSource,
  },
  {
    id: "popover",
    title: "Popover",
    description: "Inline floating detail panels for secondary content.",
    sourcePath: "components/ui/popover.tsx",
    docsHref: docs("popover"),
    preview: PopoverCatalogDemo,
    source: popoverSource,
  },
  {
    id: "tooltip",
    title: "Tooltip",
    description: "Quick hints layered above frosted controls.",
    sourcePath: "components/ui/tooltip.tsx",
    docsHref: docs("tooltip"),
    preview: TooltipCatalogDemo,
    source: tooltipSource,
  },
  {
    id: "command",
    title: "Command",
    description: "A command surface for search-first navigation and actions.",
    sourcePath: "components/ui/command.tsx",
    docsHref: docs("command"),
    preview: CommandCatalogDemo,
    source: commandSource,
    notes:
      "Built on cmdk and designed to compose naturally with Dialog for command-palette flows.",
  },
  {
    id: "scroll-area",
    title: "Scroll Area",
    description: "Custom scrolling containers that stay visually soft.",
    sourcePath: "components/ui/scroll-area.tsx",
    docsHref: docs("scroll-area"),
    preview: ScrollAreaCatalogDemo,
    source: scrollAreaSource,
  },
]
